import type { PromptDefinition } from "./types";

/**
 * Predefined greeting and learning prompts.
 * Add entries here (and matching i18n strings) — selection logic stays unchanged.
 */
export const LEARNING_PROMPTS = [
  {
    id: "greeting.morning",
    type: "greeting",
    title: "greeting.morning.title",
    message: "greeting.morning.message",
    category: "greeting",
    timeOfDay: "morning",
  },
  {
    id: "greeting.afternoon",
    type: "greeting",
    title: "greeting.afternoon.title",
    message: "greeting.afternoon.message",
    category: "greeting",
    timeOfDay: "afternoon",
  },
  {
    id: "greeting.evening",
    type: "greeting",
    title: "greeting.evening.title",
    message: "greeting.evening.message",
    category: "greeting",
    timeOfDay: "evening",
  },
  {
    id: "greeting.welcomeBack",
    type: "greeting",
    title: "greeting.welcomeBack.title",
    message: "greeting.welcomeBack.message",
    category: "greeting",
  },
  {
    id: "greeting.hello",
    type: "greeting",
    title: "greeting.hello.title",
    message: "greeting.hello.message",
    category: "greeting",
  },
  {
    id: "motivation.whatToPractice",
    type: "motivation",
    title: "motivation.whatToPractice.title",
    message: "motivation.whatToPractice.message",
    category: "motivation",
  },
  {
    id: "motivation.fewMinutes",
    type: "motivation",
    title: "motivation.fewMinutes.title",
    message: "motivation.fewMinutes.message",
    category: "motivation",
  },
  {
    id: "motivation.oneStep",
    type: "motivation",
    title: "motivation.oneStep.title",
    message: "motivation.oneStep.message",
    category: "motivation",
  },
  {
    id: "motivation.curious",
    type: "motivation",
    title: "motivation.curious.title",
    message: "motivation.curious.message",
    category: "motivation",
  },
  {
    id: "language.practiceToday",
    type: "language",
    title: "language.practiceToday.title",
    message: "language.practiceToday.message",
    category: "language",
    requiresWorkspace: true,
    usesLanguage: true,
  },
  {
    id: "language.learnWords",
    type: "language",
    title: "language.learnWords.title",
    message: "language.learnWords.message",
    category: "language",
    requiresWorkspace: true,
    usesLanguage: true,
  },
  {
    id: "language.whatToLearn",
    type: "language",
    title: "language.whatToLearn.title",
    message: "language.whatToLearn.message",
    category: "language",
    requiresWorkspace: true,
    usesLanguage: true,
  },
  {
    id: "language.keepGoing",
    type: "language",
    title: "language.keepGoing.title",
    message: "language.keepGoing.message",
    category: "language",
    requiresWorkspace: true,
    usesLanguage: true,
  },
  {
    id: "activity.vocabulary",
    type: "activity",
    title: "activity.vocabulary.title",
    message: "activity.vocabulary.message",
    category: "vocabulary",
  },
  {
    id: "activity.writing",
    type: "activity",
    title: "activity.writing.title",
    message: "activity.writing.message",
    category: "writing",
  },
  {
    id: "activity.theoryOrExercise",
    type: "activity",
    title: "activity.theoryOrExercise.title",
    message: "activity.theoryOrExercise.message",
  },
  {
    id: "activity.exercise",
    type: "activity",
    title: "activity.exercise.title",
    message: "activity.exercise.message",
    category: "exercise",
  },
  {
    id: "activity.theory",
    type: "activity",
    title: "activity.theory.title",
    message: "activity.theory.message",
    category: "theory",
  },
] as const satisfies readonly PromptDefinition[];
